"""Создать таблицы vacancies vacancy_skills task_runs

Revision ID: aabdf6861c92
Revises: 
Create Date: 2026-02-22 16:12:16.002567

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'aabdf6861c92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('vacancies_fetched', sa.INTEGER(), nullable=True),
    sa.Column('vacancies_saved', sa.INTEGER(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.Column('source', sa.VARCHAR(), server_default='hh', nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('description_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('salary_from', sa.INTEGER(), nullable=True),
    sa.Column('salary_to', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('salary_from_rub', sa.INTEGER(), nullable=True),
    sa.Column('salary_to_rub', sa.INTEGER(), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=20), nullable=True),
    sa.Column('work_format', sa.VARCHAR(length=20), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('relevance_score', sa.FLOAT(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'source', name='uq_vacancy_source')
    )
    op.create_table('vacancy_skills',
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', 'skill')
    )
    # ### end Alembic commands ###

    # FTS-триггер
    op.execute("""
CREATE OR REPLACE FUNCTION update_vacancy_search() RETURNS TRIGGER AS $$
BEGIN
  NEW.description_tsv :=
    setweight(to_tsvector('russian', COALESCE(NEW.title, '')), 'A') ||
    setweight(to_tsvector('russian', COALESCE(NEW.description, '')), 'B');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""")
    op.execute("""
CREATE TRIGGER vacancy_search_update
  BEFORE INSERT OR UPDATE OF title, description ON vacancies
  FOR EACH ROW EXECUTE FUNCTION update_vacancy_search();
""")

    # Индексы
    op.create_index(
        "idx_vacancies_published", "vacancies", ["published_at"],
        postgresql_where=sa.text("published_at IS NOT NULL"),
    )
    op.create_index(
        "idx_vacancies_cursor", "vacancies",
        [sa.text("published_at DESC"), sa.text("id DESC")],
    )
    op.execute("CREATE INDEX idx_vacancies_fts ON vacancies USING GIN(description_tsv)")
    op.create_index(
        "idx_vacancies_score", "vacancies",
        [sa.text("relevance_score DESC NULLS LAST")],
    )
    op.create_index(
        "idx_vacancies_grade_format", "vacancies",
        ["grade", "work_format", "source"],
    )
    op.create_index(
        "idx_vacancies_salary", "vacancies",
        ["salary_from_rub", "salary_to_rub"],
    )
    op.create_index("idx_vacancy_skills_skill", "vacancy_skills", ["skill"])


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS vacancy_search_update ON vacancies")
    op.execute("DROP FUNCTION IF EXISTS update_vacancy_search")
    op.drop_index("idx_vacancy_skills_skill", table_name="vacancy_skills")
    op.drop_index("idx_vacancies_salary", table_name="vacancies")
    op.drop_index("idx_vacancies_grade_format", table_name="vacancies")
    op.drop_index("idx_vacancies_score", table_name="vacancies")
    op.drop_index("idx_vacancies_fts", table_name="vacancies")
    op.drop_index("idx_vacancies_cursor", table_name="vacancies")
    op.drop_index("idx_vacancies_published", table_name="vacancies")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_skills')
    op.drop_table('vacancies')
    op.drop_table('task_runs')
    # ### end Alembic commands ###
